version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - ./.db/postgres-config.sql:/docker-entrypoint-initdb.d/postgres-config.sql
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5

  cgm-handler:
    container_name: cgm-handler-container
    build:
      context: .
      target: development
    ports:
      - "9000:8080"
    environment:
      - DEXCOM_USERNAME=${DEXCOM_USERNAME}
      - DEXCOM_PASSWORD=${DEXCOM_PASSWORD}
      - DEXCOM_APPLICATION_ID=${DEXCOM_APPLICATION_ID}
      - DEXCOM_USER_LOCATION=${DEXCOM_USER_LOCATION}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    depends_on:
      - postgres

